### ISSUE TITLE
Hacer tablero de visión del producto

### ISSUE THREAD

**Issue by StivenCardonaVarelas** [StivenCardonaVarelas/EQUIP-1_RU_PPI2020#12]

**Comment by marthaduque** [comment]
corregir la visión de acuerdo a la estructura que se indica en el documento de la semana 2 de IR, corregir el titulo de grupo objetivo de interesados, no olvidar que en las carateristicas del producto deben quedar claro las funcionalidades del software de acuerdo al alcance aprobado y revisar el último beneficio.
